name: Build/release

on:
  push:
    tags:
      - v*

jobs:
  verify-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history for accurate branch checking

      - name: Verify tag commit is in main
        run: |
          # Fetch main branch (if not already fetched)
          git fetch origin main
          # Check if the tag commit is an ancestor of main
          if git merge-base --is-ancestor "$GITHUB_SHA" origin/main; then
            echo "Tag commit is in main"
          else
            echo "Tag commit is not in main. Exiting."
            exit 1
          fi

  release:
    needs: verify-main
    runs-on: ${{ matrix.os }}

    name: Build/release Electron app

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Exit if not on main branch
        if: endsWith(github.ref, 'main') == false
        run: exit -1

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GH_TOKEN }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
