name: Unit Testing

on:
  workflow_dispatch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/workflows/test-setup

      - name: Run unit tests
        # *****about the following command:******
        # see microsoft API for reference on the difference between & and &&:
        # https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.5&viewFallbackFrom=powershell-7.1#call-operator-

        # we need to pass --run to the npm testing script
        # to make sure it quits after it has finished running tests.
        # https://stackoverflow.com/a/65530483
        # you can pass arguments to npm with an extra -- for ubuntu,
        # but -- does something else for powershell, so need to put it in quotes. - oli
        run: |
          .\resources\config-neo4j.ps1 &
          sleep 10 && npm run test:unit "--" --run
